# Configure Riak connections for the Ripple library.
development:
  http_port: 9000
  pb_port: 9001
  host: 127.0.0.1
  source: <%= Rails.root + "../riak-1.0.2/bin" %>

# The test environment has additional keys for configuring the
# Riak::TestServer for your test/spec suite:
#
# * bin_dir specifies the path to the "riak" script that you use to
#           start Riak (just the directory)
# * js_source_dir specifies where your custom Javascript functions for
#           MapReduce should be loaded from. Usually app/mapreduce.
test:
  http_port: 9100
  pb_port: 9101
  host: 127.0.0.1
  source: <%= Rails.root + "../riak-1.0.2/bin" %>
  js_source_dir: <%= Rails.root + "app/mapreduce" %>

production:
  http_port: 8098
  pb_port: 8087
  host: 127.0.0.1
